### ISSUE TITLE
[DEV]  Development roadmap

### ISSUE THREAD

**Issue by Mxrcon** [biosharp-dotnet/sucuri-api#6]
# Sucuri Development Roadmap

As suggest by @abhi18av I'm creating a Roadmap with more specific tasks and possibly date milestones
so we can advance on this project and @Aryan-sharma11 will have a nice project to show as result of his internship.

So let's try to end this by the end of August, It's okay for you @Aryan-sharma11?

# Next tasks:

## Polish the module to work locally (until 01/08/2022)
Tasks for this bigger task:
- [x] Container for Test #4 #5 
- [x] Add Status code for Sucuri response https://github.com/biosharp-dotnet/sucuri-api/issues/1#issuecomment-1194070762 https://github.com/biosharp-dotnet/sucuri-api/pull/7
- [x] Create some Instructions using the Powershell function commentaries
- [x] Address the issue with the Pode server Importing the Get-Version function #12 
- [ ] [LATER] The Module should search for any conda distribution available and use it with this priority order: `micromamba>mamba>conda` https://github.com/biosharp-dotnet/sucuri-api/pull/13

## Publish the module on Powershell gallery (until 08/08/22):
For this task you'll have to do some little tricks:
- [ ] Publishable Container 
- [x] In my opinion the module should export two functions `Invoke-SucuriServer` and `Get-CondaVersion` (we can discuss the names, the focus should be on function existance) #12 
- [ ] Work on `Sucuri-Api.psd1` and `Sucuri-api.psm1`
- [x] Make sure that we can import `Sucuri-api.psm1` and start the sucuri server with commands #12 

## Work on user experience and CI/CD (until 15/08/22):
- [ ] Create CI/CD with github actions (Davi Task)
- [ ] Make sure that this module work on MacOS, Windows and Ubuntu (with github tests)
- [ ] Test `Get-Help ...`  with Sucuri module

## Work on deployment and small front end (until 30/08/22)
- [x] Deploy the sucuri module to a virtual machine (heroku, Azure, etc..) https://github.com/biosharp-dotnet/sucuri-api/pull/13
- [ ] Create a front-end with this application using `Pode-Web`
- [ ] Further tests with this environment.
